package com.ecommerce.entity;

import java.math.BigDecimal;

import jakarta.persistence.*;

/**
 * Persistence entity representing a Product in the e-commerce catalog. * This
 * class maps to the 'products' table and serves as the source of truth for item
 * details, pricing, and real-time inventory levels.
 */
@Entity
@Table(name = "products")
public class Product {

	/**
	 * Unique identifier for the product, auto-generated by the database.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * Optimistic locking version. Essential for inventory management to prevent
	 * "Race Conditions" where two simultaneous orders might attempt to decrement
	 * the same stock unit.
	 */
	@Version
	private Long version;

	/**
	 * The display name of the product.
	 */
	@Column(nullable = false)
	private String name;

	/**
	 * Detailed product description. Limited to 1000 characters to support rich
	 * marketing text.
	 */
	@Column(length = 1000)
	private String description;

	/**
	 * The current unit price. Precision of 10 and scale of 2 maintains exact
	 * financial accuracy.
	 */
	@Column(nullable = false, precision = 10, scale = 2)
	private BigDecimal price;

	/**
	 * The current quantity available in the warehouse.
	 */
	@Column(nullable = false)
	private Integer stock;

	/**
	 * The category used for filtering and organizing the storefront.
	 */
	private String category;

	/**
	 * URL pointing to the product's primary display image.
	 */
	@Column(name = "image_url")
	private String imageUrl;

	
	private Double rating;

	// Getters and Setters

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Integer getStock() {
		return stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public Double getRating() {
		return rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}
}