package com.ecommerce.entity;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;
import jakarta.persistence.Id;

/**
 * Persistence entity representing a User within the E-Commerce system. * This
 * class serves as the central identity for the application, linking
 * authentication credentials, authorization roles, and personal commerce data
 * like shopping carts and order history.
 */
@Entity
@Table(name = "users")
public class User {

	/**
	 * Unique identifier for the user, auto-generated by the database.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * The user's full name.
	 */
	@Column(nullable = false)
	private String name;

	/**
	 * Unique email address used for login and notifications. An index is created to
	 * ensure no two users can register with the same email.
	 */
	@Column(unique = true, nullable = false)
	private String email;

	/**
	 * The hashed password for the user account. This field is generally excluded
	 * from DTOs to maintain security.
	 */
	@Column(nullable = false)
	private String password;

	/**
	 * Assigned system role (CUSTOMER or ADMIN). Stored as a String in the database
	 * to ensure the enum value is human-readable.
	 */
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	private Role role;

	/**
	 * One-to-One relationship with the Cart entity. * cascade = CascadeType.ALL:
	 * Deleting a user will automatically remove their cart.
	 * 
	 * @JsonIgnore: Prevents infinite loops during JSON serialization.
	 */
	@JsonIgnore
	@OneToOne(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
	private Cart cart;

	/**
	 * One-to-Many relationship representing the user's order history. Fetched
	 * lazily to optimize memory usage when just the user profile is required.
	 */
	@OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
	private List<Order> orders = new ArrayList<>();

	// Getters and Setters

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Cart getCart() {
		return cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	public List<Order> getOrders() {
		return orders;
	}

	public void setOrders(List<Order> orders) {
		this.orders = orders;
	}
}